apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    Version: 1.0.0
  name: sss-ng
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    Version: 1.0.0
  type: NodePort
status:
  loadBalancer: {}
